server:
  port: 8099

jwt:
  secret: "should be very-very-secret key"
  expiration: "86400"

spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5434/test"
    username: "eugen"
    password: "lopolop"
  flyway:
    url: "jdbc:postgresql://localhost:5434/test"
    user: "eugen"
    password: "lopolop"
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver